name: pattern
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  connectivity_plus: ^2.3.4
  cupertino_icons: ^1.0.2
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.9
  google_fonts: ^2.1.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  qr_flutter: ^4.0.0
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/flutter_logo.png"
  android: true
  ios: true
  web: true

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
